version: "2"

services:
    orderer.ian.com:
        container_name: orderer.ian.com
        extends:
            file: peer-base.yaml
            service: orderer-base
        volumes:
            - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ../crypto-config/ordererOrganizations/ian.com/orderers/orderer.ian.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/ian.com/orderers/orderer.ian.com/tls/:/var/hyperledger/orderer/tls
            - orderer.ian.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050

    peer0.citizen.ian.com:
        container_name: peer0.citizen.ian.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.citizen.ian.com
            - CORE_PEER_ADDRESS=peer0.citizen.ian.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.citizen.ian.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.identityauthority.ian.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.citizen.ian.com:7051
            - CORE_PEER_LOCALMSPID=CitizenMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.citizen.ian.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/citizen.ian.com/peers/peer0.citizen.ian.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/citizen.ian.com/peers/peer0.citizen.ian.com/tls:/etc/hyperledger/fabric/tls
            - peer0.citizen.ian.com:/var/hyperledger/production
        ports:
            - 7051:7051

    peer0.identityauthority.ian.com:
        container_name: peer0.identityauthority.ian.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.identityauthority.ian.com
            - CORE_PEER_ADDRESS=peer0.identityauthority.ian.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.identityauthority.ian.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.identityauthority.ian.com:8051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.citizen.ian.com:7051
            - CORE_PEER_LOCALMSPID=IdentityAuthorityMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.identityauthority.ian.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/identityauthority.ian.com/peers/peer0.identityauthority.ian.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/identityauthority.ian.com/peers/peer0.identityauthority.ian.com/tls:/etc/hyperledger/fabric/tls
            - peer0.identityauthority.ian.com:/var/hyperledger/production
        ports:
            - 8051:8051

    caCitizen:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-citizen
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.citizen.ian.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=7054
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.citizen.ian.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/citizen.ian.com/ca/:/etc/hyperledger/fabric-ca-server-config

    caIdentityAuthority:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-identityauthority
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.identityauthority.ian.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=8054
        ports:
            - "8054:8054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.identityauthority.ian.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/identityauthority.ian.com/ca/:/etc/hyperledger/fabric-ca-server-config
