---
Organizations:
    - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/ian.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

    - &Citizen
      Name: CitizenMSP
      ID: CitizenMSP
      MSPDir: crypto-config/peerOrganizations/citizen.ian.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.peer', 'CitizenMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CitizenMSP.admin')"

    - &IdentityAuthority
      Name: IdentityAuthorityMSP
      ID: IdentityAuthorityMSP
      MSPDir: crypto-config/peerOrganizations/identityauthority.ian.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('IdentityAuthorityMSP.admin', 'IdentityAuthorityMSP.peer', 'IdentityAuthorityMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('IdentityAuthorityMSP.admin', 'IdentityAuthorityMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('IdentityAuthorityMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.ian.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    IANOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Citizen
                    - *IdentityAuthority

    IANChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Citizen
                - *IdentityAuthority
            Capabilities:
                <<: *ApplicationCapabilities
